trigger:
  branches:
    include:
      - main

stages:
  - stage: Dev
    displayName: 'Deploy to Dev Environment'
    jobs:
      - job: DeployDev
        steps:
          - script: echo "Deploying to Dev environment"
          - script: echo "Run unit tests in Dev"

  - template: trigger-test-pipeline.yaml
    parameters:
      environment: dev
      dependsOn: Dev

  - stage: QA
    displayName: 'Deploy to QA Environment'
    dependsOn: Dev
    jobs:
      - job: DeployQA
        steps:
          - script: echo "Deploying to QA"
          - script: echo "Run integration and functional tests"

  - template: trigger-test-pipeline.yaml
    parameters:
      environment: qa
      dependsOn: QA

  - stage: Stage
    displayName: 'Deploy to Stage Environment'
    dependsOn: QA
    jobs:
      - job: DeployStage
        steps:
          - script: echo "Deploying to Stage"
          - script: echo "Perform smoke tests"

  - template: trigger-test-pipeline.yaml
    parameters:
      environment: stage
      dependsOn: Stage
