parameters:
  - name: environment
    type: string
  - name: dependsOn
    type: string

stages:
  - stage: TriggerTestPipeline_${{ parameters.environment }}
    displayName: 'Trigger Test Pipeline for ${{ parameters.environment }}'
    dependsOn: ${{ parameters.dependsOn }}
    jobs:
      - job: Trigger_${{ parameters.environment }}
        steps:
          - task: Bash@3
            inputs:
              targetType: 'inline'
              script: |
                echo "Triggering test pipeline in Repo B for ${{ parameters.environment }}..."
                curl -X POST \
                  -H "Content-Type: application/json" \
                  -H "Authorization: Bearer $(System.AccessToken)" \
                  https://dev.azure.com/ORG_NAME/PROJECT_NAME/_apis/pipelines/PIPELINE_ID/runs?api-version=7.1-preview.1 \
                  -d '{
                        "resources": {
                          "repositories": {
                            "self": {
                              "refName": "refs/heads/main"
                            }
                          }
                        },
                        "templateParameters": {
                          "environment": "${{ parameters.environment }}"
                        }
                      }'
